# Copyright (c) 2020 Intel Corporation.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: '3.6'

services:
  ## Define MQTT-Export service
  sparkplug-bridge:
    depends_on:
      - ia_eiibase
      - uwc_common
    build:
      context: $PWD/../uwc/sparkplug-bridge/
      dockerfile: $PWD/../uwc/sparkplug-bridge/Dockerfile
      args:
        EII_VERSION: ${EII_VERSION}
        UWC_VERSION: ${UWC_VERSION}
        EII_UID: ${EII_UID}
        EII_USER_NAME: ${EII_USER_NAME}
        BUILD_NUMBER: ${BUILD_NUMBER}
        UBUNTU_IMAGE_VERSION: ${UBUNTU_IMAGE_VERSION}
        CMAKE_INSTALL_PREFIX: ${EII_INSTALL_PATH}
    image: ${DOCKER_REGISTRY}openedgeinsights/sparkplug-bridge:${UWC_VERSION}
    container_name: sparkplug-bridge
    hostname: sparkplug-bridge
    read_only: true
    restart: unless-stopped
    ulimits:
     rtprio:
       soft: "99" # these are the maximum values of priorites to be used inside the container application
       hard: "99"
    environment:
      AppName: "SPARKPLUG-BRIDGE"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${eii_no_proxy},${ETCD_HOST}
      ETCD_HOST: ${ETCD_HOST}
      ETCD_CLIENT_PORT: ${ETCD_CLIENT_PORT}
      ETCD_PREFIX: ${ETCD_PREFIX}
      Log4cppPropsFile: "/opt/intel/config/log4cpp.properties"
      DEVICES_GROUP_LIST_FILE_NAME: "Devices_group_list.yml"
      INTERNAL_MQTT_URL: "${MQTT_PROTOCOL}://mqtt_container:11883"
      NETWORK_TYPE: "ALL"
      TOPIC_SEPARATOR: '-'
      BUILD_NUMBER: ${BUILD_NUMBER}
      PROFILING_MODE: ${PROFILING_MODE}
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: "10m"
    user: ${EII_UID}
    volumes:
     - "${EII_INSTALL_PATH}/uwc_data:/opt/intel/eii/uwc_data:ro"
     - "${EII_INSTALL_PATH}/uwc_data/common_config:${EII_INSTALL_PATH}/uwc_data/common_config:ro"
     - "${EII_INSTALL_PATH}/container_logs/sparkplug-bridge:/opt/intel/app/logs"
     - ./Certificates/SPARKPLUG-BRIDGE:/run/secrets/SPARKPLUG-BRIDGE
     - ./Certificates/rootca:/run/secrets/rootca      
     - ./Certificates/mymqttcerts:/run/secrets/mymqttcerts
     - ./Certificates/scada_ext_certs:/run/secrets/scada_ext_certs
     - "${EII_INSTALL_PATH}/sockets:${SOCKET_DIR}"
    security_opt:
      - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "/bin/sh","-c", "ps -C SPARKPLUGBRIDGE >/dev/null && echo Running || echo Not running; exit 1"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 0s
    networks:
      - eii      


