# Copyright (c) 2021 Intel Corporation.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: '3.6'

services:
  modbus-rtu-master:
    depends_on:
    - ia_eiibase
    - uwc_common
    build:
      context: $PWD/../uwc/modbus-master/
      dockerfile: $PWD/../uwc/modbus-master/Dockerfile_RTU
      args:
        EII_VERSION: ${EII_VERSION}
        EII_UID: ${EII_UID}
        EII_USER_NAME: ${EII_USER_NAME}
    image: ${DOCKER_REGISTRY}modbus-rtu-master:${EII_VERSION}
    container_name: modbus-rtu-master
    hostname: modbus-rtu-master
    read_only: true
    restart: unless-stopped
    ulimits:
      rtprio:
        soft: "99" # these are the maximum values of priorites to be used inside the container application
        hard: "99"
    environment:
      AppName: "RTU"
      ETCD_HOST: ${ETCD_HOST}
      # ETCD_HOST: ${HOST_IP} to be discussed for network mode or not.
      ETCD_CLIENT_PORT: ${ETCD_CLIENT_PORT}
      ETCD_PREFIX: ${ETCD_PREFIX}
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${eii_no_proxy},${ETCD_HOST}
      Log4cppPropsFile: "/opt/intel/config/log4cpp.properties"
      MY_APP_ID: 2
      CUTOFF_INTERVAL_PERCENTAGE: 90
      SERIAL_PORT_RETRY_INTERVAL: 1
      CertType: "zmq"
      PROFILING_MODE: ${PROFILING_MODE}
      NETWORK_TYPE: RTU
      DEVICES_GROUP_LIST_FILE_NAME: "Devices_group_list.yml"
    networks:
      - eii
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"
    volumes:
    - "${EII_INSTALL_PATH}/uwc_data:/opt/intel/eii/uwc_data:ro"
    - "vol_uwc_socket:${SOCKET_DIR}:z"
    - "${EII_INSTALL_PATH}/uwc_data/common_config:${EII_INSTALL_PATH}/uwc_data/common_config:ro"
    - "${EII_INSTALL_PATH}/container_logs/modbus-rtu-master:/opt/intel/app/logs"
    user: ${EII_UID}
    # userns_mode: host
    devices:
      - /dev:/dev
    privileged: true
    secrets:
      - ca_etcd
      - etcd_RTU_cert
      - etcd_RTU_key
    security_opt:
    - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "/bin/sh", "-c", "ps -C ModbusMaster >/dev/null && echo\
          \ Running || echo Not running; exit 1"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 0s

volumes:
  vol_uwc_socket:
    driver: local
    driver_opts:
      type: local
      o: bind
      device: ${EII_INSTALL_PATH}/sockets

secrets:
  etcd_root_cert:
    file: provision/Certificates/root/root_client_certificate.pem
  etcd_root_key:
    file: provision/Certificates/root/root_client_key.pem
  etcd_RTU_cert:
    file: provision/Certificates/RTU/RTU_client_certificate.pem
  etcd_RTU_key:
    file: provision/Certificates/RTU/RTU_client_key.pem
